export default {
    SAVE_USER:'SAVE_USER',
    SAVE_REFS:'SAVE_REFS',
    UPDATE_JOBS:'UPDATE_JOBS',
    UPDATE_COMMENTS:'UPDATE_COMMENTS',
}

export type ActionType = 'SAVE_USER' | 'UPDATE_JOBS' | 'UPDATE_COMMENTS' | 'SAVE_REFS'